name: CI

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

jobs:
    main:
        name: Nx Cloud - Main Job
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11
        with:
            number-of-agents: 3
            parallel-commands: |
                pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
                pnpm exec nx-cloud record -- pnpm exec nx format:check
            parallel-commands-on-agents: |
                pnpm exec nx affected --target=lint --parallel=3
                pnpm exec nx affected --target=test --parallel=3 --configuration=ci
                pnpm exec nx affected --target=build --parallel=3

    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11
        with:
            number-of-agents: 3
